#pragma once
/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#pragma once

#include <string>
#include "scanner.h"

namespace Lox {
    class Application {
        private:
            int numberOfArgs = 0;
            char **args = nullptr;
            Scanner scanner;
        public:
            Application(const int numberOfArgs,char **args);
            int Run();
            int RunPrompt();
    };
}